<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<?php
/*
Plugin name: WP Translate
Plugin URI: http://www.google.com
Description: A plugin have a check and translate language
Author: Supphachok Phetkaew
Author URI: http://www.google.com
*/

function wp_translate_page(){
global $wptranslate_options;
ob_start();?>

<div class="wrap">

<form action="#" method="POST">
<p>
<h1>Translate Team Football Version 1.0</h1>
</p>

<?php

$input_team_th =''; // ป้อนค่าภาษาไทยเพื่อแปลเป็นอังกฤษ

$list_team_en = array(
	//Euro 2016 (National Team)
	"ฝรั่งเศส" => "France",
	"อังกฤษ" => "English",
	"สาธารณรัฐเช็ก" => "Czech Republic",
	"ไอซ์แลนด์" => "Iceland",
	"ไอซ์แลนด์เหนือ" => "Northern Ireland",
	"ออสเตรีย" => "Austria",
	"โปรตุเกส" => "Portugal",
	"สเปน" => "Spain",
	"สวิตเซอร์แลนด์" => "Switzerland",
	"อิตาลี่" => "Italy",
	"เบลเยี่ยม" => "Belgium",
	"เวลส์" => "Wales",
	"โรมาเนีย" => "Romania",
	"แอลเบเนีย" => "Albania",
	"เยอร์มนี" => "Germany",
	"โปแลนด์" => "Poland",
	"รัสเซีย" => "Russia",
	"สโลวาเกีย" => "Slovakia",
	"โครเอเชีย" => "Croatia",
	"ตุรกี" => "Turkey",
	//English 2016-2017 (Premier Leage)
	"มิดเดิลสโปรห์" => "Middlesbrough",
	"เวสต์ บรอมมิช อัลเบียน" => "West Bromwich Albion",
	"อาร์เซน่อล" => "Arsenal",
	"เชลซี" => "Chelsea",
	"ลิเวอร์พูล" => "Liverpool",
	"แมนเชสเตอร์ ซิตี้" => "Manchester City",
	"แมนซิ" => "Manchester City",
	"แมนเชสเตอร์ ยูไนเต็ด" => "Manchester United",
	"แมนยู" => "Manchester United",
	"เซาแธมป์ตัน" => "Southampton",
	"เอฟเวอร์ตัน" => "Everton",
	"ท็อตแน่ม ฮ็อทสเปอร์" => "Tottenham Hotspur",
	"คริสตัล พาเลซ" => "Crystal Palace",
	"เบิร์นลี่ย์" => "Burnley",
	"วัดฟอร์ด" => "Watford",
	"สโต๊ค ซิตี้" => "Stoke City",
	"เลสเตอร์ ซิตี้" => "Leicester City",
	"เวสต์แฮมยูไนเต็ด" => "West Ham United",
	"ซันเดอร์แลนด์" => "Sunderland",
	"บอร์นมัธ" => "Bournemouth",
	"ฮัลล์ ซิตี้" => "Hull City",
	"สวอนซี ซิตี้" => "Swansea City",
	//English Championship 2016-2017
	"แอสตัน วิลล่า" => "Aston Villa",
	"แบล็คเบิร์น โรเวอร์ส" => "Blackburn Rovers",
	"นิวคาสเซิ่ล ยูไนเต็ด" => "Newcastle United",
	"ฟูแล่ม" => "Fulham",
	"เบอร์มิงแฮม ซิตี้" => "Brimingham City",
	"นอริช ซิตี้" => "Norwich City",
	"ดาร์บี้ เค้าท์ตี้" => "Derby County",
	"น็อตติ้งแฮม ฟอเรสต์" => "Nottingham Forest",
	"ควีนส์ปาร์ค เรนเจอร์ส" => "Queens Park Rangers",
	"วูล์ฟแฮมป์ตัน" => "Wolverhamtop",
	"ร็อตเธอร์แฮม ยูไนเต็ด" => "Rotherham United",
	"เพรสตัน นอร์ท เอนด์" => "Preston North End",
	"ลีดส์ ยูไนเต็ด" => "Leeds United",
	"ไบรท์ตัน โฮฟ อัลเบี้ยน" => "Brighton and Hove Albion",
	"วีแกน แอธเลติก" => "Wigan Athletic",
	"คาร์ดิฟฟ์ซิตี้" => "Cardiff City",
	"เร้ดดิ้ง" => "Reading",
	"อิปสวิช ทาวน์" => "Ipswich Town",
	"เซฟฟิลด์ เว้นส์เดย์" => "Sheffield Wednesday",
	"ฮัดเดอร์ฟิลด์ ทาวน์" => "Huddersfield Town",
	"เบรนท์ฟอร์ด" => "Brentford",
	"บาร์นสลีย์" => "Barnsley",
	"บริสตอล ซิตี้" => "Bristol City",
	"เบอร์ตัน อัลเบี้ยน" => "Burton Albion",
	//Italy Serie A 2015-2016
	"ยูเวนตุส" => "Juventus",
	"นาโปลี"  => "Napoli",
	"โรม่า" => "AS Roma",
	"อินเตอร์ มิลาน" => "Inter",
	"ฟิออเรนติน่า" => "Florentina",
	"ซาสซูโอโล่" => "Sassuolo",
	"เอซี มิลาน" => "AC Milan",
	"ลาซิโอ" => "Lazio",
	"คิเอโว" => "Chievo",
	"เจนัว" => "Genoa",
	"เอ็มโปลี" => "Empoli",
	"อตาลันต้า" => "Atalanta",
	"โตริโน่" => "Torino",
	"โบโลญญ่า" => "Bologna",
	"ซามพ์โดเรีย" => "Sampdoria",
	"อูดิเนเซ่" => "Udinese",
	"ปาแลร์โม่" => "Palermo",
	"คาร์ปิ" => "Carpi",
	"โฟรซิโนเน่" => "Frosinone",
	"เวโรน่า" => "Verona",
	//Primera Division 2015-2016
	"บาร์เซโลน่า" => "Barcelona",
	"เรอัล มาดริด" => "Real Mardrid",
	"แอต มาดริด" => "Atl. Mardrid",
	"บียาร์เรอัล" => "Villarreal",
	"แอธ บิลเบา" => "Ath Bilbao",
	"เซลต้า บีโก้" => "Celta Vigo",
	"เซบีย่า" => "Sevilla",
	"มาลาก้า" => "Malaga",
	"เรอัล โซเซียดาด" => "Real Sociedad",
	"เรอัล เบติส" => "Betis",
	"บาเลนเซีย" => "Valencia",
	"ลาส ปัลมาส" => "Las Palmas",
	"เออิบาร์" => "Eibar",
	"เอสปันญ่อล" => "Espanyol",
	"ลา กอรุนญ่า" => "Dep. La Coruna",
	"สปอร์ติ้ง กิฆอน" => "Gijon",
	"กรานาด้า" => "Granada CF",
	"ราโย บาเยกาโน่" => "Rayo Vallecano",
	"เคตาเฟ่" => "Getafe",
	"เลบันเต้" => "Levante",
	//Ligue 1 2015-2016
	"เปแอสเช" => "Paris SG",
	"ลียง" => "Lyon",
	"โมนาโก" => "Monaco",
	"นีซ" => "Nice",
	"ลีลล์" => "LOSC",
	"แซงต์ เอเตียน" => "St Etienne",
	"ก็อง" => "Caen",
	"แรนส์" => "Rennes",
	"บอร์กโดซ์" => "Bordeaux",
	"อองเช่ร์" => "Angers SCO",
	"บาสเตีย" => "SC Bastia",
	"มงต์เปลลิเย่ร์" => "Montpellier",
	"มาร์กเซย" => "Marseille",
	"น็องต์" => "Nantes",
	"ลอริยองต์" => "Lorient",
	"แก็งก็อง" => "Guingamp",
	"ตูลูส" => "Toulouse",
	"แร็งส์" => "Reims",
	"กาเซเล็ก อฌักซิโอ้" => "Ajaccio",
	"ทรัวส์" => "Troyes",
	//Bundesliga 2015-2016
	"บาเยิร์น มิวนิค" => "Bayern Munich",
	"ดอร์ทมุนด์" => "Dortmund",
	"เลเวอร์คูเซ่น" => "Bayer Leverkusen",
	"มึนเช่นกลัดบัค" => "Monchengladbach",
	"ชาลเก้ 04" => "Schalke 04",
	"ไมนซ์" => "Mainz",
	"แฮร์ธ่า เบอร์ลิน" => "Hertha BSC",
	"โวล์ฟสบวร์ก" => "Wolfsburg",
	"โคโลญจน์" => "Koln",
	"ฮัมบูร์ก" => "Hamburger",
	"อิงโกลสตัดท์" => "Ingolstadt",
	"เอาก์สบวร์ก" => "Augsburg",
	"เบรเมน" => "Werder",
	"ดาร์มสตัดท์" => "Darmstadt",
	"ฮอฟเฟ่นไฮม์" => "Hoffenheim",
	"แฟร้งค์เฟิร์ต" => "Eintracht",
	"สตุ๊ดการ์ท" => "Stuttgart",
	"ฮันโนเวอร์" => "Hannover",
	//POR D1 2015-2016
	"เบนฟิก้า" => "Benfica",
	"สปอร์ติ้ง ลิสบอน" => "Sporting CP",
	"ปอร์โต้" => "Porto",
	"บราก้า" => "Braga",
	"อารัวก้า" => "Arouca",
	"ริโอ อาฟ" => "Rio Ave",
	"ปากอส เดอ เฟอร์ไรร่า" => "Racos de Ferreira",
	"เอสโตริล" => "Estoril",
	"เบเลเนนส์" => "Belenenses",
	"วิตอเรีย กิมาไรส์" => "Vitoria de Guimaraes",
	"นาซิอองนาล" => "Nacional",
	"โมไรเรนเซ่" => "Moreirense",
	"มาริติโม่" => "Maritimo",
	"เบาวิสต้า" => "Boavista",
	"ซีดี ทอนแดล่า" => "Tondela",
	"วิตอเรีย เซตูบัล" => "Vitoria de Setubal",
	"ดูเนียว มาไดร่า" => "Uniao da Madeira",
	"อคาเดมิก้า โคอิมบร้า" => "Academica",
	//SCO PR 2015-2016
	"เซลติก" => "Celtic",
	"อเบอร์ดีน" => "Aberdeen",
	"ฮาร์ทส์" => "Heart of Midlothian",
	"เซนต์ จอห์นสโตน" => "St Johnstone",
	"อินเวอร์เนสส์" => "Inverness Caledonian Thistle",
	"มาเธอร์เวลล์" => "Motherwell",
	"ดันดี" => "Dundee",
	"รอสส์ เคาน์ตี้" => "Ross County",
	"แพททริค ทริสเทล" => "Partick Thistle",
	"แฮมิลตัน" => "Hamilton",
	"คิลมาร์น็อค" => "Kilmarnock",
	"ดันดี ยูไนเต็ด" => "Dundee United",
	//HOL D1
	"พีเอสวี" => "PSV",
	"อาแจกซ์" => "AJAX",
	"เฟเยนูร์ด" => "FEYENOORD",
	"อัลค์ม่าร์" => "AZ ALKMAAR",
	"อูเทร็คท์" => "UTRECHT",
	"เฮราเคิ่ลส์" => "HERACLES",
	"โกรนิงเก้น" => "GRONINGEN",
	"ซโวลเล่" => "ZWOLLE",
	"วิเทสส์" => "VITESSE",
	"ไนจ์เมเก้น" => "NIJMEGEN",
	"เดน ฮาก" => "DEN HAAG",
	"ฮีเรน วีน" => "HEERENVEEN",
	"ทเวนเต้" => "TWENTE",
	"โรด้า" => "RODA",
	"เอ็กเซลซิเออร์" => "EXCELSIOR",
	"วิลเล่ม ทเว" => "WILLEM II",
	"เดอ กราฟสคัป" => "DE GRAAFSCHAP",
	"คัมบูร์" => "CAMBUUR",
	//BEL D1
	"คลับบรูซ" => "Club Brugge",
	"เกนค์" => "Gent",
	"อันเดอร์เลชท์" => "Anderlecht",
	"ออสเทนเด้" => "Oostende",
	"เกงค์" => "Genk",
	"ซูลเต้ วาเรเกม" => "Zulte Waregem",
	"วตองดาร์ด ลีแอซ" => "Standard Liege",
	"ชาเลอร์รัว" => "Charleroi",
	"คอร์ไทรจ์" => "Kortrijk",
	"เมเชเลน" => "Mechelen",
	"โลเคอเรน" => "Lokeren",
	"วาสส์แลนด์ เบเวอเรน" => "Wassland-Beveren",
	"เปรูเวลซ์" => "Peruwelz",
	"แซงต์ ทรุยด็อง" => "Sint-Truiden",
	"เวสเตอร์โล" => "Westerlo",
	"อุด-เฮเวอร์ลี ลิวเวน" => "OH Leuven",
	//SWE D1
	"มัลโม่" => "Malmo",
	"นอร์โคปิ้ง" => "Norrkoping",
	"โกเตนเบิร์ก" => "Ifk Goteborg",
	"โอเรโบร" => "Orebro",
	"โซลน่า" => "Aik",
	"เอล์ฟส์บอร์ก" => "Elfsborg",
	"ฮัคเค่น" => "Hacken",
	"ซันด์สวาลล์" => "Gif Sundsvall",
	"ออสเตอร์ซุนด์" => "Ostersunds",
	"คัลมาร์" => "Kalmar",
	"เยอร์การ์เด้น" => "Djurgarden",
	"ยอนโคปิ้ง" => "Jonk. Sodra",
	"เฮลซิงบอร์ก" => "Helsingborg",
	"ฮัมมาร์บี้" => "Hammarby",
	"ฟัลเค่นเบิร์ก" => "Falkenbergs",
	"เกเฟล" => "Gefle",
	//FIN D1
	"เอชเจเค เฮลซิงกิ" => "HJK HELSINKI",
	"ไอเอฟเค มารีฮามน์" => "MARIEHAMN",
	"คูพีเอส" => "KUPS",
	"อิลเวส แทมเปเร่" => "ILVES",
	"โรพีเอส โรวานีมี่" => "ROPS",
	"วีพีเอส วาซ่า" => "VPS",
	"เอสเจเค ไซนาโจกิ" => "SJK",
	"ลาห์ติ" => "LAHTI",
	"พีเอส เคมิ คิงส์" => "PS KEMI",
	"อินเตอร์ ตูร์คู" => "INTER TURKU"
);

$input_team_th = strtr($input_team_th,$list_team_en);

echo "<br/>";

$input_team_en ='Chelsea chelsea'; // ป้อนค่าภาษาอังกฤษเพื่อแปลเป็นไทย

$change_team_en = strtolower($input_team_en);

$list_team_th = array(
	//Euro 2016 (National Team)
	"france" => "ฝรั่งเศส",
	"english" => "อังกฤษ",
	"czech republic" => "สาธารณรัฐเช็ก",
	"iceland" => "ไอซ์แลนด์",
	"northern Ireland" => "ไอซ์แลนด์เหนือ",
	"austria" => "ออสเตรีย",
	"portugal" => "โปรตุเกส",
	"spain" => "สเปน",
	"switzerland" => "สวิตเซอร์แลนด์",
	"italy" => "อิตาลี่",
	"belgium" => "เบลเยี่ยม",
	"wales" => "เวลส์",
	"romania" => "โรมาเนีย",
	"albania" => "แอลเบเนีย",
	"germany" => "เยอร์มนี",
	"poland" => "โปแลนด์",
	"russia" => "รัสเซีย",
	"slovakia" => "สโลวาเกีย",
	"croatia" => "โครเอเชีย",
	"turkey" => "ตุรกี",
	//English 2016-2017 (Premier Leage)
	"middlesbrough" => "มิดเดิลสโปรห์",
	"west bromwich albion" => "เวสต์ บรอมมิช อัลเบียน",
	"arsenal" => "อาร์เซน่อล",
	"chelsea" => "เชลซี",
	"liverpool" => "ลิเวอร์พูล",
	"manchester city" => "แมนเชสเตอร์ ซิตี้",
	"manchester united" => "แมนเชสเตอร์ ยูไนเต็ด",
	"southampton" => "เซาแธมป์ตัน",
	"everton" => "เอฟเวอร์ตัน",
	"tottenham hotspur" => "ท็อตแน่ม ฮ็อทสเปอร์",
	"crystal palace" => "คริสตัล พาเลซ",
	"burnley" => "เบิร์นลี่ย์",
	"watford" => "วัดฟอร์ด",
	"stoke city" => "สโต๊ค ซิตี้",
	"leicester City" => "เลสเตอร์ ซิตี้",
	"west ham united" => "เวสต์แฮมยูไนเต็ด",
	"sunderland" => "ซันเดอร์แลนด์",
	"bournemouth" => "บอร์นมัธ",
	"hull city" => "ฮัลล์ ซิตี้",
	"swansea city" => "สวอนซี ซิตี้",
	//English Championship 2016-2017
	"aston villa" => "แอสตัน วิลล่า",
	"blackburn rovers" => "แบล็คเบิร์น โรเวอร์ส",
	"newcastle united" => "นิวคาสเซิ่ล ยูไนเต็ด",
	"fulham" => "ฟูแล่ม",
	"brimingham city" => "เบอร์มิงแฮม ซิตี้",
	"norwich city" => "นอริช ซิตี้",
	"derby county" => "ดาร์บี้ เค้าท์ตี้",
	"nottingham forest" => "น็อตติ้งแฮม ฟอเรสต์",
	"queens park rangers" => "ควีนส์ปาร์ค เรนเจอร์ส",
	"wolverhamtop" => "วูล์ฟแฮมป์ตัน",
	"rotherham united" => "ร็อตเธอร์แฮม ยูไนเต็ด",
	"preston north end" => "เพรสตัน นอร์ท เอนด์",
	"leeds united" => "ลีดส์ ยูไนเต็ด",
	"brighton and hove albion" => "ไบรท์ตัน โฮฟ อัลเบี้ยน",
	"wigan athletic" => "วีแกน แอธเลติก",
	"cardiff city" => "คาร์ดิฟฟ์ซิตี้",
	"reading" => "เร้ดดิ้ง",
	"ipswich town" => "อิปสวิช ทาวน์",
	"sheffield wednesday" => "เซฟฟิลด์ เว้นส์เดย์",
	"huddersfield Town" => "ฮัดเดอร์ฟิลด์ ทาวน์",
	"brentford" => "เบรนท์ฟอร์ด",
	"barnsley" => "บาร์นสลีย์",
	"bristol city" => "บริสตอล ซิตี้",
	"burton albion" => "เบอร์ตัน อัลเบี้ยน",
	//Italy Serie A 2015-2016
	"juventus" => "ยูเวนตุส",
	"napoli"  => "นาโปลี",
	"as roma" => "โรม่า",
	"unter" => "อินเตอร์ มิลาน",
	"florentina" => "ฟิออเรนติน่า",
	"sassuolo" => "ซาสซูโอโล่",
	"ac Milan" => "เอซี มิลาน",
	"lazio" => "ลาซิโอ",
	"chievo" => "คิเอโว",
	"genoa" => "เจนัว",
	"empoli" => "เอ็มโปลี",
	"atalanta" => "อตาลันต้า",
	"torino" => "โตริโน่",
	"bologna" => "โบโลญญ่า",
	"sampdoria" => "ซามพ์โดเรีย",
	"udinese" => "อูดิเนเซ่",
	"palermo" => "ปาแลร์โม่",
	"carpi" => "คาร์ปิ",
	"frosinone" => "โฟรซิโนเน่",
	"verona" => "เวโรน่า",
	//Primera Division 2015-2016
	"barcelona" => "บาร์เซโลน่า",
	"real mardrid" => "เรอัล มาดริด",
	"atl. Mardrid" => "แอต มาดริด",
	"villarreal" => "บียาร์เรอัล",
	"ath bilbao" => "แอธ บิลเบา",
	"celta vigo" => "เซลต้า บีโก้",
	"sevilla" => "เซบีย่า",
	"malaga" => "มาลาก้า",
	"real sociedad" => "เรอัล โซเซียดาด",
	"betis" => "เรอัล เบติส",
	"valencia" => "บาเลนเซีย",
	"las palmas" => "ลาส ปัลมาส",
	"eibar" => "เออิบาร์",
	"espanyol" => "เอสปันญ่อล",
	"dep. la coruna" => "ลา กอรุนญ่า",
	"gijon" => "สปอร์ติ้ง กิฆอน",
	"granada" => "กรานาด้า",
	"rayo vallecano" => "ราโย บาเยกาโน่",
	"getafe" => "เคตาเฟ่",
	"levante" => "เลบันเต้",
	//Ligue 1
	"paris SG" => "เปแอสเช",
	"lyon" => "ลียง",
	"monaco" => "โมนาโก",
	"nice" => "นีซ",
	"losc" => "ลีลล์",
	"st etienne" => "แซงต์ เอเตียน",
	"caen" => "ก็อง",
	"rennes" => "แรนส์",
	"bordeaux" => "บอร์กโดซ์",
	"angers sco" => "อองเช่ร์",
	"sc bastia" => "บาสเตีย",
	"montpellier" => "มงต์เปลลิเย่ร์",
	"marseille" => "มาร์กเซย",
	"nantes" => "น็องต์",
	"lorient" => "ลอริยองต์",
	"guingamp" => "แก็งก็อง",
	"toulouse" => "ตูลูส",
	"reims" => "แร็งส์",
	"ajaccio" => "กาเซเล็ก อฌักซิโอ้",
	"troyes" => "ทรัวส์",
	//Bundesliga 2015-2016
	"bayern munich" => "บาเยิร์น มิวนิค",
	"dortmund" => "ดอร์ทมุนด์",
	"bayer leverkusen" => "เลเวอร์คูเซ่น",
	"monchengladbach" => "มึนเช่นกลัดบัค",
	"schalke 04" => "ชาลเก้ 04",
	"mainz" => "ไมนซ์",
	"hertha bsc" => "แฮร์ธ่า เบอร์ลิน",
	"wolfsburg" => "โวล์ฟสบวร์ก",
	"koln" => "โคโลญจน์",
	"hamburger" => "ฮัมบูร์ก",
	"ingolstadt" => "อิงโกลสตัดท์",
	"augsburg" => "เอาก์สบวร์ก",
	"werder" => "เบรเมน",
	"darmstadt" => "ดาร์มสตัดท์", 
	"hoffenheim" => "ฮอฟเฟ่นไฮม์",
	"eintracht" => "แฟร้งค์เฟิร์ต",
	"stuttgart" => "สตุ๊ดการ์ท",
	"hannover" => "ฮันโนเวอร์",
	//POR D1 2015-2016
	"benfica" => "เบนฟิก้า",
	"sporting cp" => "สปอร์ติ้ง ลิสบอน",
	"porto" => "ปอร์โต้",
	"braga" => "บราก้า",
	"arouca" => "อารัวก้า",
	"rio ave" => "ริโอ อาฟ",
	"racos de ferreira" => "ปากอส เดอ เฟอร์ไรร่า",
	"estoril" => "เอสโตริล",
	"belenenses" => "เบเลเนนส์",
	"vitoria de guimaraes" => "วิตอเรีย กิมาไรส์",
	"nacional" => "นาซิอองนาล",
	"moreirense" => "โมไรเรนเซ่",
	"maritimo" => "มาริติโม่",
	"boavista" => "เบาวิสต้า",
	"tondela" => "ซีดี ทอนแดล่า",
	"vitoria de setubal" => "วิตอเรีย เซตูบัล",
	"uniao da madeira" => "ดูเนียว มาไดร่า",
	"academica" => "อคาเดมิก้า โคอิมบร้า",
	//SCO PR 2015-2016
	"celtic" => "เซลติก",
	"aberdeen" => "อเบอร์ดีน",
	"heart of midlothian" => "ฮาร์ทส์",
	"st johnstone" => "เซนต์ จอห์นสโตน",
	"inverness caledonian thistle" => "อินเวอร์เนสส์",
	"motherwell" => "มาเธอร์เวลล์",
	"dundee" => "ดันดี",
	"ross county" => "รอสส์ เคาน์ตี้",
	"partick thistle" => "แพททริค ทริสเทล",
	"hamilton" => "แฮมิลตัน",
	"kilmarnock" => "คิลมาร์น็อค",
	"dundee united" => "ดันดี ยูไนเต็ด",
	//HOL D1
	"psv" => "พีเอสวี",
	"ajax" => "อาแจกซ์",
	"feyenoord" => "เฟเยนูร์ด",
	"az alkmaar" => "อัลค์ม่าร์",
	"utrecht" => "อูเทร็คท์",
	"heracles" => "เฮราเคิ่ลส์",
	"groningen" => "โกรนิงเก้น",
	"zwolle" => "ซโวลเล่",
	"vitesse" => "วิเทสส์",
	"nijmegen" => "ไนจ์เมเก้น",
	"den haag" => "เดน ฮาก",
	"heerenveen" => "ฮีเรน วีน",
	"twente" => "ทเวนเต้",
	"roda" => "โรด้า",
	"excelsior" => "เอ็กเซลซิเออร์",
	"willem ii" => "วิลเล่ม ทเว",
	"de  graafschap" => "เดอ กราฟสคัป",
	"cambuur" => "คัมบูร์",
	//BEL D1
	"club brugge" => "คลับบรูซ",
	"gent" => "เกนค์",
	"anderlecht" => "อันเดอร์เลชท์",
	"oostende" => "ออสเทนเด้",
	"genk" => "เกงค์",
	"zulte waregem" => "ซูลเต้ วาเรเกม",
	"standard liege" => "วตองดาร์ด ลีแอซ",
	"charleroi" => "ชาเลอร์รัว",
	"kortrijk" => "คอร์ไทรจ์",
	"mechelen" => "เมเชเลน",
	"lokeren" => "โลเคอเรน",
	"wassland-beveren" => "วาสส์แลนด์ เบเวอเรน",
	"peruwelz" => "เปรูเวลซ์",
	"sint-truiden" => "แซงต์ ทรุยด็อง",
	"westerlo" => "เวสเตอร์โล",
	"oh leuven" => "อุด-เฮเวอร์ลี ลิวเวน",
	//SWE D1
	"malmo" => "มัลโม่",
	"norrkoping" => "นอร์โคปิ้ง",
	"ifk goteborg" => "โกเตนเบิร์ก",
	"orebro" => "โอเรโบร",
	"aik" => "AIK โซลน่า",
	"elfsborg" => "เอล์ฟส์บอร์ก",
	"hacken" => "ฮัคเค่น",
	"gif sundsvall" => "ซันด์สวาลล์",
	"ostersunds" => "ออสเตอร์ซุนด์",
	"kalmar" => "คัลมาร์",
	"djurgarden" => "เยอร์การ์เด้น",
	"jonk. sodra" => "ยอนโคปิ้ง",
	"helsingborg" => "เฮลซิงบอร์ก",
	"hammarby" => "ฮัมมาร์บี้",
	"falkenbergs" => "ฟัลเค่นเบิร์ก",
	"gefle" => "เกเฟล",
	//FIN D1
	"hjk helsinki" => "เอชเจเค เฮลซิงกิ",
	"mariehamn" => "มารีฮามน์",
	"kups" => "คูพีเอส",
	"ilves" => "อิลเวส่",
	"rops" => "โรพีเอส",
	"vps" => "วีพีเอส",
	"sjk" => "เอสเจเค ไซนาโจกิ",
	"lahti" => "ลาห์ติ",
	"ps kemi" => "พีเอส เคมิ คิงส์",
	"inter turku" => "อินเตอร์ ตูร์คู"
);

$input_team_en = strtr($change_team_en,$list_team_th);

echo $input_team_en;

?>
</form>

<?php

echo ob_get_clean();
}

//admin tab

function wp_translate_tab(){

add_options_page('wp_translate_tab','WP Translate','manage_options','wptranslate','wp_translate_page');

}
add_action('admin_menu','wp_translate_tab');

//register settings

function wp_translate_setting(){

register_setting('wptranslategroup','wptranslatesettings');

}
add_action('admin_init','wp_translate_setting');


function sct_trans_th($name)
{
	return $input_team_th; // ค่าที่นำไปแสดงผลแปลจากไทยเป็นอังกฤษ
}

function sct_trans_en($name)
{
	return $input_team_en; // ค่าที่นำไปแสดงผลแปลจากอังกฤษเป็นไทย
}
?>